#! /bin/bash

# Switch to the given virtualenv.
# Opens a new bash shell with the virtualenv activated. Exiting from this shell
#  (via ctrl+D for example) will close it.
# Assumes all vitrualenvs are in ~/dev/virtualenvs.

# Note that ~/.bashrc is run *after* activating the virtualenv; you might want
# to make your $PS1 depend on $VIRTUAL_ENV

# A more complex solution with lots of bells and whistles may be found at:
#   http://pypi.python.org/pypi/virtualenvwrapper

rcfile=`tempfile`
echo ". ~/dev/virtualenvs/$1/bin/activate" >> $rcfile
echo ". ~/.bashrc" >> $rcfile
bash --rcfile $rcfile
rm $rcfile
