#! /bin/bash
# Colorize occurrences of a given regular expression
# A vgrep helper (see http://catb.org/jargon/html/V/vgrep.html)

# From http://unix.stackexchange.com/questions/366/convince-grep

grep --color -E '$|'"$@"
