#! /usr/bin/env python3

"""Pull a pull-request from GitHub or Pagure"""

import sys
import subprocess

args = sys.argv[1:]

if len(args) == 1:
    remote = 'origin'
    pr_number = int(args[0])
elif len(args) == 2:
    remote = args[0]
    pr_number = int(args[1])
else:
    print(f'{__doc__}\n\nUSAGE: {sys.argv[0]} [REMOTE] PR_NUMBER', file=sys.stderr)
    exit(1)

subprocess.run(['git', 'pull', remote, f'refs/pull/{pr_number}/head'],
               check=True)

