#! /bin/bash

DOC="Pull the given Pull Request, assuming the 'origin' remote is a Pagure or GitHub repository"

number="$1"
shift

if [ "$number" == "" ]; then
    echo "$DOC" >&2
    echo "Usage: $0 PRNUMBER" >&2
    exit 1
fi

set -ex

git pull origin refs/pull/$number/head $*
