#! /bin/bash
# Say stuff in English

awk '/^[^\!]/{gsub(/'\''/,"'\''\\'\'''\''");system("echo '\''" $0 "'\''|iconv -f utf8 -t ISO8859-2 |text2wave >tmp.wav;mplayer tmp.wav")} /^[\!]/{gsub(/'\''/,"'\''\\'\'''\''");system("echo '\''" $0 "'\''|iconv -f utf8 -t ISO8859-2 |text2wave -eval \"(voice_kal_diphone)\">tmp.wav;mplayer tmp.wav")}'

