#! /bin/bash
# Take a snapshot with the laptop camera
# CAREFUL! Outputs a PNG file

DIR=`mktemp -d`
pushd $DIR >/dev/null
mplayer tv:// -frames 20 -vo png >/dev/null 2>&1
cat *020.png
rm *
popd
rmdir $DIR
